### ISSUE TITLE
Support Data Integrity Signatures/Proof

### ISSUE THREAD

**Issue by andorsk** [TBD54566975/ssi-sdk#256] opened 2022-11-24 20:06 UTC
I was running through https://w3c-ccg.github.io/vp-request-spec/#the-did-authentication-query-format and it mentions Data Integrity Proofs: https://www.w3.org/community/reports/credentials/CG-FINAL-data-integrity-20220722/. I would think it would be good to eventually support this once it's more mature.

**Comment by decentralgabe** [comment] 2022-11-24 20:25
Thanks @andorsk I'm going to close this as a duplicate of https://github.com/TBD54566975/ssi-sdk/issues/196

Data Integrity Signatures are currently supported https://github.com/TBD54566975/ssi-sdk/blob/main/cryptosuite/cryptosuite.go

For now just with a single suite `JsonWebSignature2020` -- https://github.com/TBD54566975/ssi-sdk/blob/main/cryptosuite/jwssignaturesuite.go

**Closed by decentralgabe** 2022-11-24 20:25 UTC
Labels: enhancement

**Comment by andorsk** [comment] 2022-11-24 21:08
Ah. sorry. I didn't see that. Thanks for clarifying.
